### ISSUE TITLE
Unable to package program with xmldiff as exe

### ISSUE THREAD

**Issue by vadefac** [Shoobx/xmldiff#57] opened 2019-10-25 13:08 UTC
Hi, I have tried to package my program as an exe with both pyinstaller and Nuitka. They successfully create the executable but when I try to run it, the program fails at the xmldiff import with the following error. 

File  "\gat.dist\gat.py", line 9, in <module>
 File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "\gat.dist\xmldiff\main.py", line 9, in <module xmldiff.main>
  File "\gat.dist\pkg_resources\__init__.py", line 892, in require
  File "\gat.dist\pkg_resources\__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'xmldiff' distribution was not found and is required by the application

**Comment by regebro** [comment] 2019-11-01 12:48
I can confirm that this does not work, and neither does cx_freeze, however, I don't think that's a bug with xmldiff. I've tried to found information about the errors I get from the various tools, but I can't find anything. I think you need to talk to pyinstaller people to figure out what it going on.

**Comment by ItsCinnabar** [comment] 2020-02-13 21:02
This bug is due to the way xmldiff uses pkg_resources in main.py. There's nothing wrong with it, but pyinstaller is unable to handle things that like. It's no big deal, a simple hook file for pyinstaller will handle it. I submitted the PR, they should accept soon enough hopefully.

https://github.com/pyinstaller/pyinstaller/pull/4680

For now, if you simply make this py file and include a --additional-hooks-dir= flag you can create exes.

**Comment by Legorooj** [comment] 2020-02-16 22:26
@ItsCinnabar @regebro yes this is a hook problem. Unfortunately we can't offer support for this, but will accept PRs with a fix.

**Comment by regebro** [comment] 2024-01-04 11:27
This has been merged, I'm assuming it's now fixed.

**Closed by regebro** 2024-01-04 11:27 UTC
Labels: upstream, support
