### ISSUE TITLE
xmldiff unhappy with valid xml

### ISSUE THREAD

**Issue by doug-rosser** [Shoobx/xmldiff#27] opened 2018-11-08 22:28 UTC
Versions
```
PS C:\Users\drosser\Documents\VS-Code\Python\xmldiff> python -V
Python 3.6.5
PS C:\Users\drosser\Documents\VS-Code\Python\xmldiff> xmldiff -v
xmldiff 2.2
```

Error message
```
PS C:\Users\drosser\Documents\VS-Code\Python\xmldiff> xmldiff.exe .\file1.xml .\file2.xml
Traceback (most recent call last):
  File "c:\users\drosser\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\drosser\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\Scripts\xmldiff.exe\__main__.py", line 9, in <module>
  File "c:\users\drosser\appdata\local\programs\python\python36\lib\site-packages\xmldiff\main.py", line 110, in run
    formatter=formatter)
  File "c:\users\drosser\appdata\local\programs\python\python36\lib\site-packages\xmldiff\main.py", line 50, in diff_files
    diff_options=diff_options, formatter=formatter)
  File "c:\users\drosser\appdata\local\programs\python\python36\lib\site-packages\xmldiff\main.py", line 35, in _diff
    left_tree = parse_method(left, parser)
  File "src\lxml\etree.pyx", line 3426, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1186, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 639, in lxml.etree._raiseParseError
  File "C:\Users\drosser\Documents\VS-Code\Python\xmldiff\file1.xml", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

file1.xml
```
<?xml version="1.0" encoding="utf-8"?>
<WebTest Name="SysAdmin_GetReports_1" Id="65acf326-a724-4a0e-ba73-2f2ae3a0b83f" Owner="" Priority="2147483647" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="WebTest11.2cbebd93-337e-4958-9aed-9c1a44372ff9.rec.webtestresult" ResultsLocale="">
  <Items>
    <Request Method="GET" Guid="3b24a9a3-a9fd-4181-a03e-ed4373764d42" Version="1.1" Url="http://api.bing.com/qsml.aspx" ThinkTime="0" Timeout="300" ParseDependentRequests="True" FollowRedirects="True" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="0" ExpectedResponseUrl="https://api.bing.com/qsml.aspx?query=p&amp;maxwidth=32765&amp;rowheight=20&amp;sectionHeight=160&amp;FORM=IESS4A&amp;market=en-US" ReportingName="" IgnoreHttpStatusCode="False">
      <QueryStringParameters>
        <QueryStringParameter Name="query" Value="p" RecordedValue="p" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="maxwidth" Value="32765" RecordedValue="32765" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="rowheight" Value="20" RecordedValue="20" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="sectionHeight" Value="160" RecordedValue="160" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="FORM" Value="IESS4A" RecordedValue="IESS4A" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="market" Value="en-US" RecordedValue="en-US" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
      </QueryStringParameters>
    </Request>
  </Items>
  <ValidationRules>
    <ValidationRule Classname="Microsoft.VisualStudio.TestTools.WebTesting.Rules.ValidateResponseUrl, Microsoft.VisualStudio.QualityTools.WebTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" DisplayName="Response URL" Description="Validates that the response URL after redirects are followed is the same as the recorded response URL.  QueryString parameters are ignored." Level="Low" ExectuionOrder="BeforeDependents" />
    <ValidationRule Classname="Microsoft.VisualStudio.TestTools.WebTesting.Rules.ValidationRuleResponseTimeGoal, Microsoft.VisualStudio.QualityTools.WebTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" DisplayName="Response Time Goal" Description="Validates that the response time for the request is less than or equal to the response time goal as specified on the request.  Response time goals of zero will be ignored." Level="Low" ExectuionOrder="AfterDependents">
      <RuleParameters>
        <RuleParameter Name="Tolerance" Value="0" />
      </RuleParameters>
    </ValidationRule>
  </ValidationRules>
</WebTest>
```

file2.xml
```
<?xml version="1.0" encoding="utf-8"?>
<WebTest Name="SysAdmin_GetReports_2" Id="bfe39c75-4d66-43fc-ba8e-6182d3750a65" Owner="" Priority="2147483647" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="WebTest12.2445d47b-6af5-4465-9b05-0e0e6ce7fabe.rec.webtestresult" ResultsLocale="">
  <Items>
    <Request Method="GET" Guid="87c21775-807e-49ae-a706-33676854d7a8" Version="1.1" Url="http://api.bing.com/qsml.aspx" ThinkTime="0" Timeout="300" ParseDependentRequests="True" FollowRedirects="True" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="0" ExpectedResponseUrl="https://api.bing.com/qsml.aspx?query=p&amp;maxwidth=32765&amp;rowheight=20&amp;sectionHeight=160&amp;FORM=IESS4A&amp;market=en-US" ReportingName="" IgnoreHttpStatusCode="False">
      <QueryStringParameters>
        <QueryStringParameter Name="query" Value="p" RecordedValue="p" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="maxwidth" Value="32765" RecordedValue="32765" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="rowheight" Value="20" RecordedValue="20" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="sectionHeight" Value="160" RecordedValue="160" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="FORM" Value="IESS4A" RecordedValue="IESS4A" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
        <QueryStringParameter Name="market" Value="en-US" RecordedValue="en-US" CorrelationBinding="" UrlEncode="False" UseToGroupResults="False" />
      </QueryStringParameters>
    </Request>
  </Items>
  <ValidationRules>
    <ValidationRule Classname="Microsoft.VisualStudio.TestTools.WebTesting.Rules.ValidateResponseUrl, Microsoft.VisualStudio.QualityTools.WebTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" DisplayName="Response URL" Description="Validates that the response URL after redirects are followed is the same as the recorded response URL.  QueryString parameters are ignored." Level="Low" ExectuionOrder="BeforeDependents" />
    <ValidationRule Classname="Microsoft.VisualStudio.TestTools.WebTesting.Rules.ValidationRuleResponseTimeGoal, Microsoft.VisualStudio.QualityTools.WebTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" DisplayName="Response Time Goal" Description="Validates that the response time for the request is less than or equal to the response time goal as specified on the request.  Response time goals of zero will be ignored." Level="Low" ExectuionOrder="AfterDependents">
      <RuleParameters>
        <RuleParameter Name="Tolerance" Value="0" />
      </RuleParameters>
    </ValidationRule>
  </ValidationRules>
</WebTest>
```

**Comment by regebro** [comment] 2018-11-09 11:33
Strange, works for me.

You haven't saved them at UTF-16 by mistake? That's the only idea I have...

**Comment by doug-rosser** [comment] 2018-11-09 15:14
Hello!

Your response was actually quite helpful.
```
DRosser@DOUGROSSER MINGW64 ~/Documents/VS-Code/Python/xmldiff
$ file file1.xml
file1.xml: XML 1.0 document, UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators

DRosser@DOUGROSSER MINGW64 ~/Documents/VS-Code/Python/xmldiff
$ file test1.xml
test1.xml: XML 1.0 document, ASCII text, with very long lines, with CRLF line terminators
```

File test1.xml is the result of cutting and pasting the *visible* contents of file1.xml. Without the BOM (Byte Order Mark) I too get successful results.

I would be more than happy to submit a patch to allow xmldiff to correctly handle XML files with BOMs, any advice as to the correct approach would be appreciated.

Regards!

**Comment by doug-rosser** [comment] 2018-11-10 19:42
And now that I have code that removes the BOM, I have run into another issue on some non-trivial XML files.

```
PS C:\Users\drosser\Documents\VS-Code\Python\xmldiff> python .\diff_xml.py .\SysAdmin_GetReports_3.webtest .\SysAdmin_GetReports_4.webtest
Traceback (most recent call last):
  File ".\diff_xml.py", line 27, in <module>
    results = main.diff_files(file1fd, file2fd)
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\lib\site-packages\xmldiff\main.py", line 50, in diff_files
    diff_options=diff_options, formatter=formatter)
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\lib\site-packages\xmldiff\main.py", line 38, in _diff
    formatter=formatter)
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\lib\site-packages\xmldiff\main.py", line 27, in diff_trees
    return list(diffs)
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\lib\site-packages\xmldiff\diff.py", line 454, in diff
    for action in self.update_node_attr(lnode, rnode):
  File "C:\Users\drosser\AppData\Local\Programs\Python\Python36\lib\site-packages\xmldiff\diff.py", line 278, in update_node_attr
    new_keys.remove(rk)
KeyError: 'Description'
```

The xml files in question are not quite 1000 lines, so I will attempt to simplify them as much as possible before posting.

**Comment by regebro** [comment] 2018-11-12 06:08
Ah, yes, the byte order mark isn't needed in XML, of course. I do think it may be a bug in lxml that it doesn't handle it... I'll check it out.

**Comment by regebro** [comment] 2018-12-29 15:34
I checked it out, but forgot to comment here, apparently.

It's a bug in libxml.

https://bugs.launchpad.net/lxml/+bug/1463610

**Comment by regebro** [comment] 2019-02-19 13:03
I tried this, and could not reproduce this error, so it might have been fixed upstream.

xmldiff master (2.2)
libxml 2.9.4
libxslt1 1.1.29
lxml 4.2.5

**Comment by regebro** [comment] 2019-09-13 12:59
Closing.

**Closed by regebro** 2019-09-13 12:59 UTC
Labels: bug, upstream, waiting for feedback
